@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

# USER

### Exibe todos os usuarios
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### Exibe um usuario pelo id
GET {{baseUrl}}/users/11
Authorization: Bearer {{authToken}}

### Pesquisa um usuario pelo email
GET {{baseUrl}}/users/search/email?email=ru
Authorization: Bearer {{authToken}}

### Cria um usuario
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@example.com",
  "password": "senha123"
}

# NEWS

### Exibe todas as noticias
GET {{baseUrl}}/news

### Exibe uma noticia pelo id
GET {{baseUrl}}/news/6

### Cria uma noticia
POST {{baseUrl}}/news
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Melhores mangas da atualidadefdsfsdf",
  "content": "Com a cultura japonesa de ler mangas cada vez maisfdsf presente no mundo, separamos entao um compilado dos melhores ...",
  "tags": ["japao", "manga", "recomendacao"],
  "isActive": true
}

### Atualiza uma noticia
PATCH  {{baseUrl}}/news/7
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
 "title": "Melhores mangas da atualidade",
  "content": "Com a cultura japonesa de ler mangas cada vez mais presente no mundo, separamos entao um compilado dos melhores ...",
  "tags": ["japao", "manga", "recomendacao"],
  "isActive": true
}

### Deleta uma noticia
DELETE {{baseUrl}}/news/8
Authorization: Bearer {{authToken}}


# CATEGORY

### Exibe todas as categorias
GET {{baseUrl}}/category

### Exibe uma categoria pelo id
GET {{baseUrl}}/category/9

### Cria uma categoria
POST {{baseUrl}}/category
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "filosofia"
}

### Deleta uma categoria
DELETE {{baseUrl}}/category/10
Authorization: Bearer {{authToken}}


# BOOK

### Exibe um livro pelo id
GET {{baseUrl}}/books/9

### Cria um livro
POST {{baseUrl}}/books
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "The Art of War",
  "author": "Sun Tzu",
  "publisher": "Simon & Schuster",
  "year": -500,
  "isbn": "978-1590302255",
  "synopsis": "An ancient Chinese military treatise that provides guidance on military strategy and tactics, which has influenced both military and business thinking.",
  "availability": true,
  "quantity": 6,
  "category": 13
}

### Atualiza um livro
PATCH  {{baseUrl}}/books/5
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "The Hobbit"
}

### Deleta um livro
DELETE {{baseUrl}}/books/6
Authorization: Bearer {{authToken}}

### Pesquisar um livro
GET {{baseUrl}}/books/search





# EVENTS

### Exibe todos os eventos
GET {{baseUrl}}/library-events

### Exibe um evento pelo id
GET {{baseUrl}}/library-events/3

### Cria um evento
POST {{baseUrl}}/library-events
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "fsdfsf",
  "description": "Test event with empty title",
  "date": "2024-07-15T14:00:00Z",
  "location": "Main Library",
  "banner": "test.jpg",
  "seats": 30
}

### Atualiza um evento
PATCH  {{baseUrl}}/library-events/3
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Digital Research Workshop"
}

### Deleta um evento
DELETE {{baseUrl}}/library-events/7
Authorization: Bearer {{authToken}}

### Registra um usuario para um evento
POST {{baseUrl}}/library-events/5/register
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "userId": 12
}

### Ve os registros no evento
GET {{baseUrl}}/library-events/3/registrations
Authorization: Bearer {{authToken}}

### Ve todos o eventos que o usuario esta cadastrado
GET {{baseUrl}}/library-events/user/12/events
Authorization: Bearer {{authToken}}

### Cancela o registro
DELETE {{baseUrl}}/library-events/3/registrations/12
Authorization: Bearer {{authToken}}


# REQUEST

### Exibe todos os requests
GET {{baseUrl}}/requests
Authorization: Bearer {{authToken}}

### Cria um request
POST {{baseUrl}}/requests
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "publisher": "Scribner",
  "year": 1925,
  "genre": "Classic Fiction"
}

### Deleta um request
DELETE {{baseUrl}}/requests/6
Authorization: Bearer {{authToken}}


# LOAN

### Cria um loan
POST {{baseUrl}}/loans
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "userId": 14,
  "bookId": 3
}

### Pega o loan por id
GET {{baseUrl}}/loans/3
Authorization: Bearer {{authToken}}

### Pega todos os loan 
GET {{baseUrl}}/loans/findAll/?status=renewed
Authorization: Bearer {{authToken}}

### Pega o livro
PUT {{baseUrl}}/loans/5/pickup
Authorization: Bearer {{authToken}}

### Renova o emprestimo
PUT {{baseUrl}}/loans/5/renew
Authorization: Bearer {{authToken}}

### Retorna o livro
PUT {{baseUrl}}/loans/5/return
Authorization: Bearer {{authToken}}

### Pega todos os emprestimos do usuario
GET {{baseUrl}}/loans/user/12?status=picked_up
Authorization: Bearer {{authToken}}

### Pega as estatisticas dos esmprestimos
GET {{baseUrl}}/loans/statistics
Authorization: Bearer {{authToken}}

### Pega o livro diretamente na biblioteca
GET {{baseUrl}}/loans/directly/3/11
Authorization: Bearer {{authToken}}



# AUTH

### Loga um usuario
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "senha123"
}
